version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - 27017
    networks:
      - app
  rabbitmq:
    image: rabbitmq:3.8.9
    ports:
      - "5672:5672"
    expose:
      - 5672
    networks:
      - app

networks:
  app:
    driver: bridge
