/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ScheduleRecurrentEmailsBodySchema {
  /**
   * Send mail to
   */
  emailTo: string;
  /**
   * Mail subject
   */
  subject: string;
  /**
   * Message to sent
   */
  message: string;
  /**
   * Time of the day when to send the mail in format HH:mm
   */
  tickTime: string;
  dayOfMonth?: number;
  weekdays?: ("Sunday" | "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday")[];
  whenToStopMails: {
    /**
     * When to stop sending those recurrent mails
     */
    whenToStop: "never" | "onDate" | "afterSomeOccurency";
    /**
     * Date on which to stop sending mails
     */
    stopDate?: string;
    /**
     * After those number of sent mails to stop sending
     */
    occurrancy?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
